### ISSUE TITLE
Ajout mode broker distant

### ISSUE THREAD

**Issue by Francky62** [WoCha-FR/jeedom-linky#6]
Bonjour Wocha, 

J'utilise tes plugins et aucun problème avec un broker local , mais aucun ne fonctionne avec un broker distant via mqttmanager 

J'utilise un broker distant car j'utilise Jeedom et HA,  toute mon installation est dispo sur les deux systemes , cela permet aussi de rien perdre lors de maj raté de l'un ou l'autre ou de remettre rapidement  .

Cela permet aussi de faire moins de requête pour netatmo par exemple ...

Si je publie via jeedom dans le broker, je récupère sur un autre système 
C'est ce que j'ai voulu faire avec mqttlinky mais impossible , j'ai fait l'inverse actuellement .
Le module est connecté sur mon HA et je publie dans le broker, je récupère du coup dans mqttmanager les messages. Ce qui permet de continuer a utiliser suivi conso et garder mon historique. 

J'espere que c'est clair, si tu as des question, n'hesite pas. 

Merci

**Comment by WoCha-FR** [comment]
Bonsoir.
Fonctionnement bien compris.
Je vais regarder cela de plus prêt pour implémenter cette nouvelle fonctionnalité.
Merci de votre patience.

**Comment by Francky62** [comment]
Merci de la prise en compte

**Comment by WoCha-FR** [comment]
Bonjour,
Je pense que ce que vous voulez est possible en natif dans jeedom sans modifications des plugins.
Voir la documentation de MQTT Manager et plus précisement la partie de lien entre broker mqtt.

**Comment by Francky62** [comment]
Bonjour
Actuellement mqtt manager fonctionne avec un broker distant, de ce coté il n'y a pas de soucis . tout est fonctionnelle 
D'autre plugins comme jeezigbee ou zwave fonctionnent trés bien via mqtt manager et donc un broker distant . 
Mais tout vos plugins ne fonctionnait pas si mqtt est connecté en distant (Je parle des plugins dans le premier message et non de mqtt manager). 
Je peux refaire des tests et donner des logs ou autres

**Comment by WoCha-FR** [comment]
Bonjour,

Je pense qu'il y à une incompréhension depuis le début.
Mes plugins n'ont jamais eu de mode "Broker Distant" mais "Librairie distante"

En clair, quand on choisi "Mode Distant" dans mes plugins, on doit installer la librairie JS sur une machine distante et on doit la configurer pour envoyer les trames MQTT sur le broker de Jeedom.

Dans votre cas, vous voulez que le plugin se connecte sur un broker distant qui reçois les trames MQTT de la librairie et en effet, celà n'est pas possible avec mes plugins.

Pour votre fonctionnement, liez votre broker distant recevant les trames MQTT de la librairie JS mqtt4teleinfo vers le broker local de votre jeedom et créer un équipement MQTT-Manager pour récupérer les informations.

Bonne journée.

**Comment by Francky62** [comment]
Bonjour merci pour la réponse , pour moi on ne s'ait pas encore bien compris meme si je comprend un peu votre fonctionnement 
Mais je vais mettre plus de detail encore et vous me direz si c'est ce vous avez dit dans le message precedent 

**Je vais tester avec domutlls par exemple qui il n'y a pas de mode distant** 

MQTT MANAGER est connecter sur un broker distant sur une autre machine, le fonctionnement est ok 

J'active domutils et lance les dependances, la librairies est sur jeedom 
du coup, dependance ok

` + echo '*******************Begin of package installation******************'
*******************Begin of package installation******************
+ touch /tmp/jeedom_install_in_progress_mqttDomutils
+ echo 1
+ echo 2
+ sudo chmod +x /var/www/html/core/class/../../plugins/mqttDomutils/resources/pre_install.sh
+ sudo /var/www/html/core/class/../../plugins/mqttDomutils/resources/pre_install.sh
+ echo 'Pre installation de l'\''installation/mise à jour des dépendances mqttDomutils'
Pre installation de l'installation/mise à jour des dépendances mqttDomutils
+ PROGRESS_FILE=/tmp/jeedom_install_in_progress_mqttDomutils
+ echo 5
+++ dirname /var/www/html/core/class/../../plugins/mqttDomutils/resources/pre_install.sh
++ cd /var/www/html/core/class/../../plugins/mqttDomutils/resources
++ pwd
+ BASEDIR=/var/www/html/plugins/mqttDomutils/resources
+ '[' -d /var/www/html/plugins/mqttDomutils/resources/mqtt4frenchtools ']'
+ '[' -d /var/www/html/plugins/mqttDomutils/resources/node_modules ']'
+ echo 15
+ echo 'Pre install finished'
Pre install finished
+ echo 3
+ php /var/www/html/core/class/../php/jeecli.php plugin install mqtt2
+ echo 4
+ sudo killall apt apt-get unattended-upgr
apt: no process found
apt-get: no process found
+ sudo rm /var/lib/apt/lists/lock
+ sudo rm /var/cache/apt/archives/lock
+ sudo rm /var/lib/dpkg/lock /var/lib/dpkg/lock-frontend
+ sudo sudo dpkg --configure -a --force-confdef
+ sudo apt update
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://security.debian.org bullseye-security InRelease [27.2 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye-backports InRelease [49.0 kB]
Hit:5 https://download.docker.com/linux/debian bullseye InRelease
Hit:6 https://deb.nodesource.com/node_18.x nodistro InRelease
Get:8 http://security.debian.org bullseye-security/main arm64 Packages [366 kB]
Get:9 http://security.debian.org bullseye-security/main armhf Packages [363 kB]
Get:10 http://deb.debian.org/debian bullseye/main arm64 Packages [10.9 MB]
Hit:7 https://packagecloud.io/ookla/speedtest-cli/debian bullseye InRelease
Get:11 http://deb.debian.org/debian bullseye-backports/main arm64 Packages.diff/Index [63.3 kB]
Get:12 http://deb.debian.org/debian bullseye-backports/main armhf Packages.diff/Index [63.3 kB]
Get:13 http://deb.debian.org/debian bullseye-backports/main all Contents (deb).diff/Index [63.6 kB]
Get:14 http://deb.debian.org/debian bullseye-backports/main arm64 Packages T-2024-09-07-2013.37-F-2024-09-07-2013.37.pdiff [1690 B]
Get:15 http://deb.debian.org/debian bullseye-backports/main armhf Packages T-2024-09-07-2013.37-F-2024-09-07-2013.37.pdiff [1691 B]
Get:14 http://deb.debian.org/debian bullseye-backports/main arm64 Packages T-2024-09-07-2013.37-F-2024-09-07-2013.37.pdiff [1690 B]
Get:15 http://deb.debian.org/debian bullseye-backports/main armhf Packages T-2024-09-07-2013.37-F-2024-09-07-2013.37.pdiff [1691 B]
Get:16 http://deb.debian.org/debian bullseye-backports/main all Contents (deb) T-2024-09-07-2013.37-F-2024-09-07-2013.37.pdiff [132 B]
Get:16 http://deb.debian.org/debian bullseye-backports/main all Contents (deb) T-2024-09-07-2013.37-F-2024-09-07-2013.37.pdiff [132 B]
Get:17 http://deb.debian.org/debian bullseye/main armhf Packages [10.8 MB]
Get:18 http://deb.debian.org/debian bullseye/main all Contents (deb) [31.3 MB]
Get:19 http://deb.debian.org/debian bullseye/main arm64 Contents (deb) [9886 kB]
Get:20 http://deb.debian.org/debian bullseye/main armhf Contents (deb) [9358 kB]
Get:21 http://deb.debian.org/debian bullseye/non-free arm64 Packages [88.3 kB]
Get:22 http://deb.debian.org/debian bullseye/non-free arm64 Contents (deb) [38.8 kB]
Fetched 73.6 MB in 17s (4312 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
152 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ echo 5
+ sudo chmod +x /var/www/html/core/class/../../resources/install_nodejs.sh
+ sudo /var/www/html/core/class/../../resources/install_nodejs.sh
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Hit:5 https://deb.nodesource.com/node_18.x nodistro InRelease
Hit:6 https://download.docker.com/linux/debian bullseye InRelease
Hit:7 https://packagecloud.io/ookla/speedtest-cli/debian bullseye InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
apt-utils is already the newest version (2.2.4).
build-essential is already the newest version (12.9).
lsb-release is already the newest version (11.1.0).
Suggested packages:
git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
gitweb git-cvs git-mediawiki git-svn
The following packages will be upgraded:
git
1 upgraded, 0 newly installed, 0 to remove and 151 not upgraded.
Need to get 5493 kB of archives.
After this operation, 373 kB of additional disk space will be used.
Get:1 http://security.debian.org bullseye-security/main arm64 git arm64 1:2.30.2-1+deb11u3 [5493 kB]
Fetched 5493 kB in 1s (8043 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 68153 files and directories currently installed.)
Preparing to unpack .../git_1%3a2.30.2-1+deb11u3_arm64.deb ...
Unpacking git (1:2.30.2-1+deb11u3) over (1:2.30.2-1+deb11u2) ...
Setting up git (1:2.30.2-1+deb11u3) ...
[Check Version NodeJS actuelle : v18.19.0 : [  OK  ]
[Check Prefix : /usr and sudo prefix : /usr and www-data prefix : /usr : [  OK  ]
+ echo 6
+ sudo chmod +x /var/www/html/core/class/../../plugins/mqttDomutils/resources/post_install.sh
+ sudo /var/www/html/core/class/../../plugins/mqttDomutils/resources/post_install.sh
+ echo 'Post installation de l'\''installation/mise à jour des dépendances mqttDomutils'
Post installation de l'installation/mise à jour des dépendances mqttDomutils
+ PROGRESS_FILE=/tmp/jeedom_install_in_progress_mqttDomutils
+ echo 50
+++ dirname /var/www/html/core/class/../../plugins/mqttDomutils/resources/post_install.sh
++ cd /var/www/html/core/class/../../plugins/mqttDomutils/resources
++ pwd
+ BASEDIR=/var/www/html/plugins/mqttDomutils/resources
+ cd /var/www/html/plugins/mqttDomutils/resources
+ source ../core/config/mqttDomutils.config.ini
+ echo 'Version requise : 1.2.3'
Version requise : 1.2.3
+ npm i mqtt4frenchtools@1.2.3 --no-save
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
added 79 packages in 9s
11 packages are looking for funding
run `npm fund` for details
npm notice
npm notice New minor version of npm available! 10.2.3 -> 10.8.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.3>
npm notice Run `npm install -g npm@10.8.3` to update!
npm notice
+ echo 90
+ chown www-data:www-data -R /var/www/html/plugins/mqttDomutils/resources/node_modules
+ echo 7
+ php /var/www/html/core/class/../php/jeecli.php plugin dependancy_end mqttDomutils
+ echo 8
+ rm /tmp/jeedom_install_in_progress_mqttDomutils
+ echo '*******************End of package installation******************'
*******************End of package installation****************** `

Ensuite je lance le demon et voila l'erreur que j'ai 

`2024-09-08 08:30:08.489 <info>  Starting French Tools
2024-09-08 08:30:08.500 <error> Unable to run => See errors below
2024-09-08 08:30:08.500 <error> Error: MQTT connection error [Invalid URL] mqtt://admin:monmotdepasse@192.168.68.104:1883
at MqttClient.connect (/var/www/html/plugins/mqttDomutils/resources/node_modules/mqtt4frenchtools/lib/mqtt.js:32:13)
at main (/var/www/html/plugins/mqttDomutils/resources/node_modules/mqtt4frenchtools/index.js:72:16)
at Object.<anonymous> (/var/www/html/plugins/mqttDomutils/resources/node_modules/mqtt4frenchtools/index.js:127:1)
at Module._compile (node:internal/modules/cjs/loader:1356:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
at Module.load (node:internal/modules/cjs/loader:1197:32)
at Module._load (node:internal/modules/cjs/loader:1013:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
at node:internal/main/run_main_module:28:49`


Ma box jeedom est sur 192.168.68.116 , il essaye de se connecter au broker via mqtt manager car il a les bonnes infos mais j'ai cette erreur et cela sur tout vos plugins.

Le plugin est bien dans les "abonnés" sous mqttmanager 
voici ma configuration  https://ibb.co/Cm9Fx3G

Il ne publie pas dans le broker qui est configuré dans mqttmanger si mqtt est en distant  alors que si mqttmanager est en local, cela fonctionne trés bien

**Comment by WoCha-FR** [comment]
Bonjour,
En effet je n'avais pas du tout compris que vous n'aviez pas de broker installé sur Jeedom.
Mes modules n'ont pas été testé avec ce fonctionnement.
Ils récupèrent bien la configuration de MQTT Manager mais la librairie n'arrive pas à se connecter.
Donc je vais regarder la librairie et reviens vers vous

**Comment by Francky62** [comment]
Pas de soucis, merci 

PS : J'en avait 4 et les 4 ne fonctionnait plus au passage du broker local a distant

**Comment by WoCha-FR** [comment]
Re,
Je viens de faire le test et je n'ai pas le même résultat.
Jeedom sur 10.42.1.99 avec mqttManager en mode broker distant sur 10.42.1.6
MqttDomutils installé en mode local avec log en mode débug

Log du plugin : 
```
[2024-09-08 10:53:42] DEBUG  : [deamon_start] Informations reçues de MQTT Manager : {"ip":"10.42.1.6","port":"1883","protocol":"mqtt","user":"wochauser","password":"wochapassword"}
[2024-09-08 10:53:42] INFO  : Démarrage du démon mqttDomutils :  /usr/bin/node /var/www/html/plugins/mqttDomutils/resources/node_modules/mqtt4frenchtools/index.js -z -u mqtt://wochauser:wochapassword@10.42.1.6:1883 -t domutils -v debug
``` 

Log du démon : 
```
2024-09-08 10:53:42.689 <info>  Starting French Tools
2024-09-08 10:53:42.727 <info>  Connected to MQTT broker [mqtt://10.42.1.6:1883]
2024-09-08 10:53:42.729 <debug> Publish frame to topic [domutils/global/saints]
``` 

Test sur une debian 11.11 & Jeedom 4.4.15

**Comment by Francky62** [comment]
Si je compare

Debian 11.8 (J'avais fait le post en en debian 10 donc pas de changement )
Jeedom 4.4.13
Box Atlas 
Avec domutils
log plugin 

`[2024-09-08 17:00:07] DEBUG  : [deamon_start] Informations reçues de MQTT Manager : {"ip":"192.168.68.104","port":"1883","protocol":"mqtt","user":"admin","password":"xxxxxxxxxx"}
[2024-09-08 17:00:07] INFO  : Démarrage du démon mqttDomutils :  /usr/bin/node /var/www/html/plugins/mqttDomutils/resources/node_modules/mqtt4frenchtools/index.js -z -u mqtt://admin:xxxxxxx@192.168.68.104:1883 -t domutils -v debug`

log demon (rouge) 

`2024-09-08 17:00:08.934 <info>  Starting French Tools
2024-09-08 17:00:08.945 <error> Unable to run => See errors below
2024-09-08 17:00:08.946 <error> Error: MQTT connection error [Invalid URL] mqtt://admin:xxxxxxx@192.168.68.104:1883
at MqttClient.connect (/var/www/html/plugins/mqttDomutils/resources/node_modules/mqtt4frenchtools/lib/mqtt.js:32:13)
at main (/var/www/html/plugins/mqttDomutils/resources/node_modules/mqtt4frenchtools/index.js:72:16)
at Object.<anonymous> (/var/www/html/plugins/mqttDomutils/resources/node_modules/mqtt4frenchtools/index.js:127:1)
at Module._compile (node:internal/modules/cjs/loader:1356:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
at Module.load (node:internal/modules/cjs/loader:1197:32)
at Module._load (node:internal/modules/cjs/loader:1013:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
at node:internal/main/run_main_module:28:49`

J'ai testé avec netatmo par exemple 

Log plugin 

`[2024-09-08 16:55:26] DEBUG  : [deamon_start] Informations reçues de MQTT Manager : {"ip":"192.168.68.104","port":"1883","protocol":"mqtt","user":"admin","password":"xxxxxxxxxxxx"}
[2024-09-08 16:55:26] INFO  : Démarrage du démon mqttNetatmo : NETATMO_LOGLVL=debug /usr/bin/node /var/www/html/plugins/mqttNetatmo/resources/netatmo-mqtt/netatmo-mqtt.js`

Log du demon (bizarre qu'il soit vert et aucun equipement n'ai remontée) 

`2024-09-08T14:53:32.973Z DEBUG] Config: {"mqtt_url":"mqtt://admin:xxxxxxxxx@192.168.68.104:1883","mqtt_topic":"netatmo","mqtt_verifcert":false,"clientId":"66ddba085002fcb40d096443","clientSecret":"IMYwGYSR7TY8Bgr30wTOONZlhMa","getFavorites":false}
[2024-09-08T14:54:14.562Z WARN] State file /var/www/html/plugins/mqttNetatmo/resources/netatmo-mqtt/state.json not found. No saved state data available.
[2024-09-08T14:54:14.636Z DEBUG] Successfully saved updated state file: /var/www/html/plugins/mqttNetatmo/resources/netatmo-mqtt/state.json
[2024-09-08T14:54:14.638Z DEBUG] Attempting connection to Netatmo using generated refresh token...
[2024-09-08T14:54:14.638Z DEBUG] accessToken valid
[2024-09-08T14:54:14.640Z DEBUG] Attempting connection to MQTT broker...
[2024-09-08T14:54:14.821Z ERROR] Unable to connect to MQTT broker getaddrinfo ENOTFOUND admin
[2024-09-08T14:54:15.830Z INFO] Attempting to reconnect to MQTT broker...
[2024-09-08T14:54:15.843Z ERROR] Unable to connect to MQTT broker getaddrinfo ENOTFOUND admin
[2024-09-08T14:54:16.845Z INFO] Attempting to reconnect to MQTT broker...
[2024-09-08T14:54:16.857Z ERROR] Unable to connect to MQTT broker getaddrinfo ENOTFOUND admin
[2024-09-08T14:54:17.857Z INFO] Attempting to reconnect to MQTT broker...
[2024-09-08T14:54:17.873Z ERROR] Unable to connect to MQTT broker getaddrinfo ENOTFOUND admin
[2024-09-08T14:54:18.875Z INFO] Attempting to reconnect to MQTT broker...`


Et rien sur mqtt du coup 
https://ibb.co/tshX57b

**Comment by WoCha-FR** [comment]
```
Unable to connect to MQTT broker getaddrinfo ENOTFOUND admin
``` 
J'ai l'impression que sur votre machine, la librairie MQTT des plugins prends "admin" pour l'adresse du serveur.
Quelle est votre version de NodeJS ?
Vous avez bien la dernière version des plugins et leurs dépendances à jour ?
Merci.

**Comment by Francky62** [comment]
Node v18.19.0
Les plugins sont a jour, je les ai réinstallé pour vous donner des infos 

J'avais tout supprimé comme il ne fonctionnait plus
